version: '3'
services:
  social-media-platform:
    container_name: social-media-platform
    restart: always
    build: .
    ports:
      - '80:80'
    depends_on:
      - mongoapp

  mongoapp:
    container_name: mongoapp
    image: mongo
    ports:
      - '27017:27017'