version: '3.7'

services:
  node:
    container_name: social-media-platform
    image: social-media-platform
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    networks:
      - social-media-platform-network
    environment:
      - NODE_ENV=production
    depends_on: 
      - mongodb
      
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - social-media-platform-network

networks:
  social-media-platform-network:
    driver: bridge